NumPy, short for Numerical Python, is a fundamental open-source library in Python for scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a comprehensive collection of high-level mathematical functions designed to operate efficiently on these arrays

In [47]:
import numpy as np


In [48]:
array = np.array('A')
print(np.ndim(array))

0


In [49]:
array = np.array(['A','B','C'])
print(np.ndim(array))

1


In [50]:
array_2 = np.array([['A','B','C'],
                  ['D','E','F'],
                  ['F','G','H']])
print(np.ndim(array_2))

2


In [51]:
array_3 = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                  [['j','k','l'],['M','N','O'],['P','Q','R']],
                  [['S','T','U'],['V','W','X'],['Y','Z',' ']]])
print(np.ndim(array_3))

3


In [52]:
print(array_3.shape)

(3, 3, 3)


In [53]:
print(array_3[0][0][0])

A


In [54]:
print(array_3[0,0,2])

C


In [55]:
print(array_3[0,1,1])

E


In [56]:
print(array_3[1,1,1])

N


In [ ]:
# Concatenation
word = array_3[2,0,0]  + array_3[0,0,0] + array_3[0,2,2]
print(word)

SAI


In [58]:
# Create a array using numpy
# Create a 1-D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [59]:
# 1-D array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 Row and 5 columns

array([[1, 2, 3, 4, 5]])

In [60]:
# 2-D array
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [61]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [62]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Slicing in Numpy

In [78]:
import numpy as np
array = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

# Array Slicing array[start:end:step]
print(array[1])
print(array[0:3])


[5 6 7 8]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [79]:
print(array[0:4:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [80]:
print(array[::-1])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [81]:
print(array[:,0])

[ 1  5  9 13]


In [82]:
print(array[:,-1])

[ 4  8 12 16]


In [83]:
print(array[:, 0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [84]:
print(array[:, 1:4])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [85]:
print(array[:, ::2])

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [86]:
print(array[:, ::-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [87]:
print(array[0:2,0:2])

[[1 2]
 [5 6]]


In [88]:
print(array[0:2,2:])

[[3 4]
 [7 8]]


In [90]:
print(array[2:,0:2])

[[ 9 10]
 [13 14]]


In [91]:
print(array[2:,2:])

[[11 12]
 [15 16]]


### Scalar Arithmetic

In [63]:
# identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
# Numpy vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise addition
print("Addition: ",arr1 + arr2)
print("Substraction: ",arr1 - arr2)
print("Multiplication: ",arr1 * arr2)



Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]


In [65]:
# Universal Functions
arr = np.array([1,2,3,4,5])
# square root
print(np.sqrt(arr))
# Exponential
print(np.exp(arr))
# Sine
print(np.sin(arr))
# Natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [66]:
# Array Slicing and indexing
array1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", array1)


Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [67]:
print(array1[0][0])

1


In [68]:
print(array1[1: ,2: ])

[[ 7  8]
 [11 12]]


In [69]:
print(array1[0:2,2:])

[[3 4]
 [7 8]]


In [70]:
print(array1[1:,1:3])

[[ 6  7]
 [10 11]]


In [71]:
# Modify Array elements
array1[0,0] = 100
print(array1)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [72]:
array1[1:] = 100
print(array1)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [73]:
# Statistical concepts normalization
data = np.array([1,2,3,4,5])
# Calculate Mean and standard Deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalize_data = (data - mean) / std_dev
print("Normalized data: ",normalize_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [74]:
data = np.array([1,2,3,4,5])
# Calculate Mean and standard Deviation
mean = np.mean(data)
print("Mean: ",mean)
std_dev = np.std(data)
print("Standard Deviation: ",mean)
median = np.median(data)
print("Median : ",mean)
variance = np.var(data)
print("Variance : ",variance)

Mean:  3.0
Standard Deviation:  3.0
Median :  3.0
Variance :  2.0


In [75]:
# Logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data >= 5) & (data <= 8)]


array([5, 6, 7, 8])