NumPy, short for Numerical Python, is a fundamental open-source library in Python for scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a comprehensive collection of high-level mathematical functions designed to operate efficiently on these arrays

In [3]:
import numpy as np


In [4]:
# Create a array using numpy
# Create a 1-D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
# 1-D array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 Row and 5 columns

array([[1, 2, 3, 4, 5]])

In [6]:
# 2-D array
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [7]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
# identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# Numpy vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise addition
print("Addition: ",arr1 + arr2)
print("Substraction: ",arr1 - arr2)
print("Multiplication: ",arr1 * arr2)



Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]


In [11]:
# Universal Functions
arr = np.array([1,2,3,4,5])
# square root
print(np.sqrt(arr))
# Exponential
print(np.exp(arr))
# Sine
print(np.sin(arr))
# Natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [12]:
# Array Slicing and indexing
array1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", array1)


Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
print(array1[0][0])

1


In [18]:
print(array1[1: ,2: ])

[[ 7  8]
 [11 12]]


In [20]:
print(array1[0:2,2:])

[[3 4]
 [7 8]]


In [28]:
print(array1[1:,1:3])

[[ 6  7]
 [10 11]]


In [30]:
# Modify Array elements
array1[0,0] = 100
print(array1)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [31]:
array1[1:] = 100
print(array1)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [34]:
# Statistical concepts normalization
data = np.array([1,2,3,4,5])
# Calculate Mean and standard Deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalize_data = (data - mean) / std_dev
print("Normalized data: ",normalize_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [37]:
data = np.array([1,2,3,4,5])
# Calculate Mean and standard Deviation
mean = np.mean(data)
print("Mean: ",mean)
std_dev = np.std(data)
print("Standard Deviation: ",mean)
median = np.median(data)
print("Median : ",mean)
variance = np.var(data)
print("Variance : ",variance)

Mean:  3.0
Standard Deviation:  3.0
Median :  3.0
Variance :  2.0


In [41]:
# Logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data >= 5) & (data <= 8)]


array([5, 6, 7, 8])